### ISSUE TITLE
Get au domain?

### ISSUE THREAD

**Issue by lwjohnst86** [au-cru/site#14]
So it is like cru.au.dk? 

@knielbo you mentioned during the meeting this is possible. How easy is it to get and how can set it up?

**Comment by lwjohnst86** [comment]
Based on [this](https://typo3.au.dk/en/support/formularer/order_website/) it doesn't seem likely or easy at this stage to have a custom domain with AU.

**Comment by adivea** [comment]
I have emailed Radomir@au.dk with request for domain for my own auff project. I will let you know how it goes. If I succeed, I'll request one on behalf of au-cru.
